/arborist_node:
  ros__parameters:
    max_objects_per_second: 0.14
    max_pictures_per_second: 0.5
    task_qa_window: 8
    power_qa_window: 8
    bt_filename: "onlyID.xml"
    experiment_name: "defaultEXP"

