/sample_arborist_node:
  ros__parameters:
    action_name: "behavior_server" # Optional (defaults to `bt_action_server`)
    behavior_trees:
      - rebet_samples/trees
    plugins:
      - rebet_samples/bt_plugins
